sudo: required
services:
  - docker

before_install:
  - docker build -t l87freeman/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true l87freeman/docker-react npm run test -- --coverage